### ISSUE TITLE
Called children on a leaf node

### ISSUE THREAD

**Issue by MattSucich** [SagaHealthcareIT/mirthsync#3]
#2 seems to be the same as this but it was closed.

i'm noticing this happens with every import unless i log into mirth and disassociate all channels from their groups and do a push again:

![image](https://user-images.githubusercontent.com/10262739/63798435-aeec0680-c8cf-11e9-92e5-8d2da22fa456.png)

In another scenario - i can delete one group and all its channels - it still fails with the exact same error. viewing the server, i can see that the channel groups get created and no channels have been imported yet before it fails.

**Comment by jessesaga** [comment]
In the release that you're using the error handling isn't very descriptive.

Could you let me know if you experience the same issue with this snapshot release? - https://github.com/SagaHealthcareIT/mirthsync/releases/tag/2.0.3-SNAPSHOT

Please note that many things have changed in the recent snapshot release and the on-disk format is a little different. You'll want to try using it with an empty local target directory rather than a directory already populated from the 'pull' of the previous mirthSync release.
